# レビュー検出パターン設定ファイル
# FANZA商品ページのレビュー検出用正規表現パターン

review_patterns:
  # 基本パターン（厳密版）
  basic:
    - pattern: 'レビュー\s*[（(]\s*(\d+)\s*件\s*[）)]'
      description: 'レビュー（5件）'
      
    - pattern: 'レビュー\s*:\s*(\d+)\s*件'
      description: 'レビュー: 5件'
      
    - pattern: 'レビュー\s+(\d+)\s*件'
      description: 'レビュー 5件'
      
    - pattern: '評価\s*[（(]\s*(\d+)\s*件\s*[）)]'
      description: '評価（5件）'
      
    - pattern: '口コミ\s*[（(]\s*(\d+)\s*件\s*[）)]'
      description: '口コミ（5件）'

  # 2024年対応パターン
  modern:
    - pattern: '(\d+)\s*件のレビュー'
      description: '5件のレビュー'
      
    - pattern: '(\d+)\s*件の評価'
      description: '5件の評価'
      
    - pattern: '(\d+)\s*人がレビュー'
      description: '5人がレビュー'
      
    - pattern: '(\d+)\s*人の評価'
      description: '5人の評価'
      
    - pattern: 'レビュー数\s*[:：]\s*(\d+)'
      description: 'レビュー数: 5'
      
    - pattern: '評価数\s*[:：]\s*(\d+)'
      description: '評価数: 5'

  # 英語パターン
  english:
    - pattern: '(\d+)\s+reviews?\b'
      description: '5 reviews（単語境界）'
      
    - pattern: '(\d+)\s+ratings?\b'
      description: '5 ratings（単語境界）'
      
    - pattern: 'Reviews?\s*[（(]\s*(\d+)\s*[）)]'
      description: 'Reviews (5)'

  # FANZA特有パターン
  fanza_specific:
    - pattern: 'この作品のレビュー\s*[（(]\s*(\d+)\s*[）)]'
      description: 'この作品のレビュー（5）'
      
    - pattern: 'ユーザー評価\s*[（(]\s*(\d+)\s*[）)]'
      description: 'ユーザー評価（5）'

# HTML内のレビューセクション用パターン
review_section_patterns:
  # 新しいFANZA形式（2024-2025）
  - pattern: '総評価数\s*(\d+)\s*[（(]'
    description: '総評価数 1（1件のコメント）'
    
  - pattern: '総評価数\s*(\d+)'
    description: '総評価数 1'
    
  - pattern: '平均評価\s*[\d.]+\s*総評価数\s*(\d+)'
    description: '平均評価 4.5 総評価数 2'
    
  # 従来パターン
  - pattern: '(\d+)\s*件のレビュー'
    description: '5件のレビュー'
    
  - pattern: 'レビュー\s*(\d+)\s*件'
    description: 'レビュー 5件'
    
  - pattern: '(\d+)\s*人のレビュー'
    description: '5人のレビュー'
    
  - pattern: '全\s*(\d+)\s*件'
    description: '全 5件'
    
  - pattern: 'レビュー数:\s*(\d+)'
    description: 'レビュー数: 5'

# レビューなし判定パターン
no_review_indicators:
  - 'この作品に最初のレビューを書いてみませんか？'
  - '最初のレビューを書いて'
  - '最初のレビューを投稿'
  - 'Be the first to review'
  - 'Write the first review'

# HTMLセレクタ
html_selectors:
  - '.review-list'
  - '.review-item'
  - '[class*="review-count"]'
  - '[class*="rating-count"]'
  - '[data-review-count]'

# キーワード
keywords:
  - '件'
  - 'レビュー'
  - 'review'
  - '評価'